version: "1.0"

services:
  schedule-service:
    container_name: schedule-service
    build: /schedule_service
    networks:
      - default
    depends_on:
      - api-service
    volumes:
      - ./logs:/app/logs

  api-service:
    container_name: api-service
    build: /api_service
    networks:
      - default
    ports:
      - 5000:5000
    hostname: api-service
    volumes:
      - ./logs:/app/logs
